/* Generated By:JavaCC: Do not edit this line. miniC.java */
import java.util.*;
import java.io.*;

public class miniC implements miniCConstants {

    private static Stack<pair> expStack = new Stack<pair>();
    private static Stack<Object> ss = new Stack<Object>();
    private static Stack<ScopeLevel> currentScope = new Stack<ScopeLevel>();
    private static Hashtable<String, String> strings = new Hashtable<String, String>();
    private static Hashtable<String, ArrayList<Code>> functions = new Hashtable<String, ArrayList<Code>>();
    private static String FonctionCourante;
    private static ArrayList<Code> Base;
    private static int k;


    public static String setString(String string) {
        String name = "STRING" + strings.size();

        StringBuilder value = new StringBuilder( "'" + string.substring(1,string.length() - 1) + "$'");

        int from = 0;
        while(value.indexOf("\\n",from) != -1)
        {
            from = value.indexOf("\\n",from);
            value.replace(from, from+"\\n".length(), "' , CR , LF , '");
            from++;
        }

        from = 0;
        while(value.indexOf("\\t",from) != -1)
        {
            from = value.indexOf("\\t",from);
            value.replace(from, from+"\\t".length(), "' , TAB , '");
            from++;
        }

        from = 0;
        while(value.indexOf("'' ,",from) != -1)
        {
            from = value.indexOf("'' ,",from);
            value.replace(from, from+"'' ,".length(), "");
            from++;
        }

        strings.put(name , value.toString());

        return name;
    }

    public static int getCurrentAddr() {
        return Scope.getCurrentAddr();
    }

    public Hashtable<String, ArrayList<Code>> Fonctions() {
        return functions;
    }


    private static void AppelFonction(String entree) throws ParseException {
        if(!functions.containsKey(entree))
        {
            throw new ParseException("Unknown function '" + entree
                + "'You have to define it first ! ");
        }
    }


    private static void FonctionDefinition(String entree) throws ParseException {
        if(functions.containsKey(entree))
        {
            throw new ParseException("Function '" + entree
                        + "' already defined ! ");
        }

        FonctionCourante = entree;

        Base = new ArrayList<Code>();
        k = 0;
        functions.put(entree,Base);
    }


    public static ArrayList<Code> getPB() {
        return Base;
    }

    public static Hashtable<String, String> getStrings() {
        return strings;
    }

    private static String getAddr(Object s) {

        if (s instanceof Integer) {
            s = (Integer) s;

            return ("RESERVE + " + s.toString());
        }

        return ((String) s).substring(1);
    }

    private static int Temp() {
        int temp = currentScope.peek().getCurrentAddr();
        currentScope.peek().setCurrentAddr(temp + 2);
        return temp;
    }

    private static String getAddr(Object s, String first) {
        String output = getAddr(s);
        if (output.startsWith("RESERVE + ")) {
            return first + output;
        }
        return output;
    }



    private static void comparer(String entree) {
        int jp3 = toInt(ss.pop());
        int jp4 = toInt(ss.pop());
        int jp10 = toInt(ss.pop());
        int jp11;

        switch (entree) {
            case "==":
                jp11 = toInt(ss.pop());
                Base.set(jp11, new Code("mov", "BX", getAddr(ss.pop())));
                Base.set(jp10, new Code("mov", "AX", getAddr(ss.pop())));
                Base.set(jp4, new Code("cmp", "AX", "BX"));
                Base.set(jp3, new Code("jne", "label" + FonctionCourante + (k), null));
                break;
            case "!=":
                jp11 = toInt(ss.pop());
                Base.set(jp11, new Code("mov", "BX", getAddr(ss.pop())));
                Base.set(jp10, new Code("mov", "AX", getAddr(ss.pop())));
                Base.set(jp4, new Code("cmp", "AX", "BX"));
                Base.set(jp3, new Code("je", "label" + FonctionCourante + (k), null));
                break;
            case "<":
                jp11 = toInt(ss.pop());
                Base.set(jp11, new Code("mov", "BX", getAddr(ss.pop())));
                Base.set(jp10, new Code("mov", "AX", getAddr(ss.pop())));
                Base.set(jp4, new Code("cmp", "AX", "BX"));
                Base.set(jp3, new Code("jge", "label" + FonctionCourante + (k), null));
                break;
            case ">":
                jp11 = toInt(ss.pop());
                Base.set(jp11, new Code("mov", "BX", getAddr(ss.pop())));
                Base.set(jp10, new Code("mov", "AX", getAddr(ss.pop())));
                Base.set(jp4, new Code("cmp", "AX", "BX"));
                Base.set(jp3, new Code("jle", "label" + FonctionCourante + (k), null));
                break;
            case ">=":
                jp11 = toInt(ss.pop());
                Base.set(jp11, new Code("mov", "BX", getAddr(ss.pop())));
                Base.set(jp10, new Code("mov", "AX", getAddr(ss.pop())));
                Base.set(jp4, new Code("cmp", "AX", "BX"));
                Base.set(jp3, new Code("jl", "label" + FonctionCourante + (k), null));
                break;
            case "<=":
                jp11 = toInt(ss.pop());
                Base.set(jp11, new Code("mov", "BX", getAddr(ss.pop())));
                Base.set(jp10, new Code("mov", "AX", getAddr(ss.pop())));
                Base.set(jp4, new Code("cmp", "AX", "BX"));
                Base.set(jp3, new Code("jg", "label" + FonctionCourante + (k), null));
                break;
        }

    }

    public static int toInt(Object obj)
    {
        if(obj instanceof Number) {
             return ((Number) obj).intValue();
        }
        String s = obj.toString();
        char[] mysChars = s.toCharArray();
        if(mysChars[0]=='#') {mysChars[0]='0';}
        s = String.valueOf(mysChars);
        return Integer.parseInt(s);
    }

    private static void GenererCode(String action, String entree, String type, String args ) throws ParseException{

        switch (action) {

            case "#createFunction":
                FonctionDefinition(entree);
                break;
            case "#AppelFonction":
                AppelFonction(entree);
                Base.add(new Code("CALL", entree,null ));
                k++;
                break;
            case "#startScopeLevel":
                currentScope.push(new ScopeLevel());
                break;
            case "#endScopeLevel":
                currentScope.pop();
                break;
            case "#scopeStart":
                currentScope.peek().addScope();
                break;
            case "#scopeEnd":
                currentScope.peek().deleteScope();
                break;
            case "#const":
                ss.push("#" + entree);
                break;
            case "#variableDef":
                int a = currentScope.peek().addVariable(entree);
                ss.push(a);
                break;
            case "#pid":
                int p = currentScope.peek().findVariable(entree);
                ss.push(p);
                break;
            case "#add":
                int t = Temp();

                Base.add(new Code("mov", "CX", getAddr(ss.pop())));
                k++;
                Base.add(new Code("add", "CX", getAddr(ss.pop())));
                k++;
                Base.add(new Code("mov", getAddr(t), "CX"));
                k++;

                ss.push(t);
                break;
            case "#mines":
                int t1 = Temp();
                String str2 = getAddr(ss.pop());
                Base.add(new Code("mov", "CX", getAddr(ss.pop())));
                k++;
                Base.add(new Code("sub", "CX", str2));
                k++;
                Base.add(new Code("mov", getAddr(t1), "CX"));
                k++;
                ss.push(t1);
                break;
            case "#mul":
                int t2 = Temp();
                Base.add(new Code("mov", "CX", getAddr(ss.pop())));
                k++;
                Base.add(new Code("mov", "AL", getAddr(ss.pop(), "BYTE PTR ")));
                k++;
                Base.add(new Code("mul", "CL", null));
                k++;
                Base.add(new Code("mov", getAddr(t2), "AX"));
                k++;
                ss.push(t2);
                break;
            case "#div":
                int t3 = Temp();
                String pa2 = getAddr(ss.pop(), "BYTE PTR ");
                Base.add(new Code("mov", "AX", getAddr(ss.pop())));
                k++;
                Base.add(new Code("mov", "CL", pa2));
                k++;
                Base.add(new Code("div", "CL", null));
                k++;
                Base.add(new Code("mov", getAddr(t3, "BYTE PTR "), "AL"));
                k++;
                ss.push(t3);
                break;
            case "#assign":
                Base.add(new Code("mov", "AX", getAddr(ss.pop())));
                k++;
                Base.add(new Code("mov", getAddr(ss.pop()), "AX"));
                k++;
                break;
            case "#label":
                Base.add(new Code("label" + FonctionCourante + k + ":", null, null));
                ss.push(k);
                k++;
                break;
            case "#save":
                Base.add(new Code("save", null, null));
                ss.push(k);
                k++;
                break;
            case "#save_pointer":
                Base.add(new Code("label" + FonctionCourante + k + ":", null, null));
                ss.push(k);
                k++;
                break;
            case "#while":
                comparer(entree);

                Base.add(new Code("jmp", "label" + FonctionCourante + ss.pop(), null));
                Base.add(new Code("label" + FonctionCourante + k + ":", null, null));
                k++;
                k++;
                break;
            case "#until":
                comparer(entree);

                Base.add(new Code("jmp", "label" + FonctionCourante + ss.pop(), null));
                Base.add(new Code("label" + FonctionCourante + k + ":", null, null));
                k++;
                k++;

                break;
            case "#jpf_save":
                comparer(entree);

                Base.add(new Code("save", null, null));
                ss.push(k);

                Base.add(new Code("label" + FonctionCourante + k + ":", null, null));
                k++;
                k++;
                break;
            case "#jp":
                Base.set(toInt(ss.pop()), new Code("jmp", "label" + FonctionCourante + k, null));
                break;
            case "#jpf":
                comparer(entree);

                Base.add(new Code("label" + FonctionCourante + k + ":", null, null));
                k++;
                break;
            case "#jp_statement":
                Base.add(new Code("jmp", null, null));
                ss.push(k);
                k++;
                break;
            case "#for_jp_statement":
                Base.add(new Code("label" + FonctionCourante + k + ":", null, null));
                ss.push(k);
                k++;
                break;
            case "#for":
                int jp_statement = toInt(ss.pop());
                int jp_condition = toInt(ss.pop());
                int step_pointer = toInt(ss.pop());
                int jp_after_condition = toInt(ss.pop());

                if(!entree.equals("nothing"))
                {
                    comparer(entree);
                }

                int befor_condition = toInt(ss.pop());

                Base.set(jp_condition, new Code("jmp", "label" + FonctionCourante + befor_condition, null));
                Base.set(jp_after_condition, new Code("jmp", "label" + FonctionCourante + jp_statement, null));

                Base.add(new Code("jmp", "label" + FonctionCourante + step_pointer, null));
                Base.add(new Code("label" + FonctionCourante + k + ":", null, null));
                k++;
                k++;
                break;
            case "#print":
                int pr = toInt(ss.pop());
                Base.add(new Code("mov", "AH", "BYTE PTR " + getAddr(pr + 1)));
                k++;
                Base.add(new Code("mov", "AL", "BYTE PTR " + getAddr(pr)));
                k++;
                Base.add(new Code("CALL", "CONVERT_ASSCII", null));
                k++;
                Base.add(new Code("mov", "AH", "09H"));
                k++;
                Base.add(new Code("lea", "DX", "ASSCII_NUM"));
                k++;
                Base.add(new Code("int", "21H", null));
                k++;
                break;
            case "#printString":
                String name = setString(entree);

                Base.add(new Code("mov", "AH", "09H"));
                k++;
                Base.add(new Code("lea", "DX", name));
                k++;
                Base.add(new Code("int", "21H", null));
                k++;
                break;
            case "#pause":

                Base.add(new Code("mov", "AH", "7H"));
                k++;
                Base.add(new Code("int", "21H", null));
                k++;
                break;
            case "#cls":
                Base.add(new Code("CALL", "CLRSCR", null));
                k++;
                break;
            case "#end":
                Base.add(new Code("label" + FonctionCourante + k + ": ", null, null));
                k++;
                int l = 0;
                System.out.println("/////////////Generation du code intermediaire\\\\\\\\\\\\");
                StringBuilder sb = new StringBuilder();
                for (Code c : Base)
                {
                    sb.append(l+" :\t");
                    sb.append(c.toString());
                    sb.append("\n");
                    l++;
                }
                System.out.println(sb);
                System.out.println("_________________________________________________________");
                break;
            case "#inc":
                Base.add(new Code("INC", getAddr(ss.pop()), null));
                k++;
                break;
            case "#dec":
                Base.add(new Code("DEC", getAddr(ss.pop()), null));
                k++;
                break;
        }

    }



    static int precedence(String opt)
    {
        switch(opt)
        {
            case "#add":
            case "#mines":
                return 1;
            case "#div":
            case "#mul":
                return 2;
            default:
                return 0;
        }
    }

    static void preStack(pair p) throws ParseException
    {
          String part1 = p.part1;
          switch(part1)
          {
                case "#add":
                case "#mines":
                case "#div":
                case "#mul":
                    while(!expStack.isEmpty() && precedence(expStack.peek().part1) >= precedence(part1))
                    {
                        pair pa = expStack.pop();
                        GenererCode(pa.part1,pa.part2, "", "");
                    }
                    expStack.push(p);
                    break;
                case "#OP":
                    expStack.push(p);
                    break;
                case "#CP":
                    while(!expStack.peek().part1.equals("#OP") )
                    {
                        pair pa = expStack.pop();
                        GenererCode(pa.part1,pa.part2, "", "");
                    }
                    expStack.pop();
                case "#finish":
                    while(!expStack.isEmpty())
                    {
                        pair pa = expStack.pop();
                        GenererCode(pa.part1,pa.part2, "", "");
                    }
                case "#pid":
                case "#const":
                    GenererCode(p.part1,p.part2, "", "");
                    break;
          }
    }

    static class pair
    {
        public static String part1 , part2;

        public pair(String part1,String part2)
        {
            this.part1 = part1;
            this.part2 = part2;
        }

    }


/*********************************
***** SECTION 2 - USER CODE *****
*********************************/


    public static void main(String args []) throws ParseException
    {

    miniC parser = new miniC(System.in);
    while (true)
    {
      System.out.println("\n*******Bienvenu dans le compilateur de MINI-C*******");

      try
      {
        System.out.println("====Votre code en MINI-C====");
        miniC.program();
      }
      catch (Exception e)
      {
        System.out.println("Syntaxic error detected ... ! ");
        System.out.println(e.getMessage());
        miniC.ReInit(System.in);
      }
      catch (Error e)
      {
        System.out.println("Error ... !");
        System.out.println(e.getMessage());
        break;
      }
    }
  }

//Grammar starts here
  static final public void program() throws ParseException {
    label_1:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_1;
      }
      code();
    }
      GenererCode( "#startScopeLevel" , "", "", "");
    jj_consume_token(TYPE);
    jj_consume_token(36);
                    GenererCode( "#createFunction" , "main", "", "" );
    jj_consume_token(PAROUVR);
    jj_consume_token(PARFERM);
    StatementBlockDef();
      GenererCode( "#end" , "", "", "");
      GenererCode( "#endScopeLevel" , "", "", "");
    jj_consume_token(0);
  }

  static final public void code() throws ParseException {
    Function();
  }

  static final public void ArgList() throws ParseException {
    Arg();
    label_2:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_2;
      }
      jj_consume_token(VIRGULE);
      Arg();
    }
  }

  static final public void Arg() throws ParseException {
    jj_consume_token(TYPE);
    jj_consume_token(IDENTIFIANT);
  }

  static final public void Function() throws ParseException {
 Token id;
      GenererCode( "#startScopeLevel" , "", "", "");
    jj_consume_token(TYPE);
    id = jj_consume_token(IDENTIFIANT);
    jj_consume_token(PAROUVR);
    if (jj_2_3(2)) {
      ArgList();
    } else {
      ;
    }
    jj_consume_token(PARFERM);
                                                                GenererCode( "#createFunction", id.image, "", "" );
    StatementBlockDef();
       GenererCode( "#end" , "", "", "");
      GenererCode( "#endScopeLevel" , "", "", "");
  }

  static final public void varAssignDefInInit() throws ParseException {
    jj_consume_token(AFFECT);
    Expr();
                     preStack(new pair( "#finish" , ""));
                                                            GenererCode( "#assign" , "", "", "" );
  }

  static final public void varDefineDef() throws ParseException {
  Token type, id;
    if (jj_2_4(2)) {
      jj_consume_token(TYPE);
      id = jj_consume_token(IDENTIFIANT);
                                     GenererCode( "#variableDef" , id.image, "", "" );
    } else if (jj_2_5(2)) {
      id = jj_consume_token(IDENTIFIANT);
                                                                                                                     GenererCode( "#pid" , id.image, "", "" );
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(AFFECT);
    ExprAffect();
                        preStack(new pair( "#finish" , "" ));
                                                                GenererCode( "#assign" , "", "", "" );
  }

  static final public void StatementBlockDef() throws ParseException {
    jj_consume_token(ACCOUVR);
                GenererCode( "#scopeStart" , "", "", "");
    label_3:
    while (true) {
      if (jj_2_6(2)) {
        ;
      } else {
        break label_3;
      }
      Stmt();
    }
                                                                         GenererCode( "#scopeEnd" , "", "", "");
    jj_consume_token(ACCFERM);
  }

  static final public void Stmt() throws ParseException {
    if (jj_2_7(2)) {
      varDefineDef();
      jj_consume_token(POINTVIRGULE);
    } else if (jj_2_8(2)) {
      Expr();
      jj_consume_token(POINTVIRGULE);
    } else if (jj_2_9(2)) {
      IfStmt();
    } else if (jj_2_10(2)) {
      ForStmt();
    } else if (jj_2_11(2)) {
      appelFonction();
    } else if (jj_2_12(2)) {
      WhileStmt();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void IfStmt() throws ParseException {
  Token op;
    jj_consume_token(IF);
    jj_consume_token(PAROUVR);
    op = Rvalue();
    jj_consume_token(PARFERM);
    StatementBlockDef();
    if (jj_2_15(2)) {
      jj_consume_token(ELSE);
                   GenererCode( "#jpf_save" , op.image, "", "" );
      if (jj_2_13(2)) {
        StatementBlockDef();
      } else if (jj_2_14(2)) {
        Stmt();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                        GenererCode( "#jp" , "", "", "" );
    } else {
          GenererCode( "#jpf" , op.image, "", "" );
    }
  }

  static final public void Expr() throws ParseException {
    if (jj_2_16(2147483647)) {
      ExprAffect();
    } else if (jj_2_17(2)) {
      Rvalue();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void ExprAffect() throws ParseException {
    if (jj_2_25(2)) {
      if (jj_2_18(2)) {
             Token id1;
        id1 = jj_consume_token(IDENTIFIANT);
                                                 preStack(new pair( "#pid" , id1.image ));
      } else if (jj_2_19(2)) {
                                                                                                Token id3;
        id3 = jj_consume_token(NOMBRE);
                                                                                                                               preStack(new pair( "#const" , id3.image ));
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      if (jj_2_24(2)) {
                  String op;
        if (jj_2_20(2)) {
          jj_consume_token(ADD);
                                preStack(new pair( "#add" , "" ));
        } else if (jj_2_21(2)) {
          jj_consume_token(SUB);
                                preStack(new pair( "#mines" , "" ));
        } else if (jj_2_22(2)) {
          jj_consume_token(MUL);
                                preStack(new pair( "#mul" , "" ));
        } else if (jj_2_23(2)) {
          jj_consume_token(DIV);
                                preStack(new pair( "#div" , "" ));
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        ExprAffect();
      } else {
        ;
      }
    } else if (jj_2_26(2)) {
      jj_consume_token(PAROUVR);
                   preStack(new pair( "#OP" , "" ));
      ExprAffect();
      jj_consume_token(PARFERM);
                                                                        preStack(new pair( "#CP" , "" ));
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public Token Rvalue() throws ParseException {
 Token op = null;
    ExprAffect();
                      preStack(new pair( "#finish" , "" ));
    if (jj_2_27(2)) {
      op = jj_consume_token(LT);
    } else if (jj_2_28(2)) {
      op = jj_consume_token(GT);
    } else if (jj_2_29(2)) {
      op = jj_consume_token(EQ);
    } else if (jj_2_30(2)) {
      op = jj_consume_token(NEQ);
    } else if (jj_2_31(2)) {
      op = jj_consume_token(37);
    } else if (jj_2_32(2)) {
      op = jj_consume_token(LTE);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    ExprAffect();
                                                                                                                                                     preStack(new pair( "#finish" , "" ));
                                                                                                                                                                                              GenererCode( "#save" , "", "", "" );GenererCode( "#save" , "", "", "" );GenererCode( "#save" , "", "", "" );GenererCode( "#save" , "", "", "" );
         {if (true) return op;}
    throw new Error("Missing return statement in function");
  }

  static final public void appelFonction() throws ParseException {
 Token id;
    id = jj_consume_token(IDENTIFIANT);
    jj_consume_token(PAROUVR);
    if (jj_2_33(2)) {
      IdentList();
    } else {
      ;
    }
    jj_consume_token(PARFERM);
                                                            GenererCode( "#AppelFonction", id.image , "", "" );
    jj_consume_token(POINTVIRGULE);
  }

  static final public void IdentList() throws ParseException {
    FuncExpr();
    label_4:
    while (true) {
      if (jj_2_34(2)) {
        ;
      } else {
        break label_4;
      }
      jj_consume_token(VIRGULE);
      FuncExpr();
    }
  }

  static final public void FuncExpr() throws ParseException {
    Expr();
  }

  static final public void WhileStmt() throws ParseException {
 Token op;
    jj_consume_token(WHILE);
    jj_consume_token(PAROUVR);
                        GenererCode( "#save_pointer" , "", "", "" );
    op = Rvalue();
    jj_consume_token(PARFERM);
    if (jj_2_35(2)) {
      StatementBlockDef();
    } else if (jj_2_36(2)) {
      Stmt();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                                                                                                GenererCode( "#while" , op.image, "", "" );
  }

  static final public void ForStmt() throws ParseException {
 Token op = null;
    jj_consume_token(FOR);
    jj_consume_token(PAROUVR);
    if (jj_2_37(2)) {
      varDefineDef();
    } else {
      ;
    }
    jj_consume_token(POINTVIRGULE);
                                                GenererCode( "#save_pointer" , "", "", "" );
    if (jj_2_38(2)) {
      op = Rvalue();
    } else {
      ;
    }
                                                                                                                    GenererCode( "#save" , "", "", "" );
    jj_consume_token(POINTVIRGULE);
                                                                                                                                                                             GenererCode( "#save_pointer" , "", "", "" );
    if (jj_2_41(2)) {
      if (jj_2_39(2)) {
                                                                                                                                                                                                                                 Token id;
        id = jj_consume_token(IDENTIFIANT);
                                                                                                                                                                                                                                                                   GenererCode( "#pid" , id.image, "", "" );
        jj_consume_token(AFFECT);
        ExprAffect();
                                                                                                                                                                                                                                                                                                                                     preStack(new pair( "#finish" , "" ));
                                                                                                                                                                                                                                                                                                                                                                              GenererCode( "#assign" , "", "", "" );
      } else if (jj_2_40(2)) {
        DeclarationIn();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } else {
      ;
    }
                                                                                                                                                                                                                                                                                                                                                                                                                                              GenererCode( "#save" , "", "", "" );
    jj_consume_token(PARFERM);
                  GenererCode( "#for_jp_statement" , "", "", "" );
    StatementBlockDef();
              if(op != null)GenererCode( "#for" , op.image, "", "" );else GenererCode( "#for" , "nothing", "", "" );
  }

  static final public void DeclarationIn() throws ParseException {
 Token id;
    id = jj_consume_token(IDENTIFIANT);
                           GenererCode( "#pid" , id.image, "", "" );
    if (jj_2_42(2)) {
      jj_consume_token(38);
                                                                               GenererCode( "#inc" , "", "", "");
    } else if (jj_2_43(2)) {
      jj_consume_token(39);
                                                                                                                            GenererCode( "#dec" , "", "", "");
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  static private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  static private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  static private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  static private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  static private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  static private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  static private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  static private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  static private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  static private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  static private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  static private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  static private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  static private boolean jj_2_37(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_37(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  static private boolean jj_2_38(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_38(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  static private boolean jj_2_39(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_39(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  static private boolean jj_2_40(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_40(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  static private boolean jj_2_41(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_41(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  static private boolean jj_2_42(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_42(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(41, xla); }
  }

  static private boolean jj_2_43(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_43(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(42, xla); }
  }

  static private boolean jj_3_10() {
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_3R_10()) return true;
    if (jj_scan_token(POINTVIRGULE)) return true;
    return false;
  }

  static private boolean jj_3R_8() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3_12()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(PAROUVR)) return true;
    return false;
  }

  static private boolean jj_3_33() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_scan_token(ACCOUVR)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_6()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(ACCFERM)) return true;
    return false;
  }

  static private boolean jj_3_38() {
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_scan_token(TYPE)) return true;
    if (jj_scan_token(IDENTIFIANT)) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) return true;
    }
    if (jj_scan_token(AFFECT)) return true;
    return false;
  }

  static private boolean jj_3_13() {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(PAROUVR)) return true;
    return false;
  }

  static private boolean jj_3_34() {
    if (jj_scan_token(VIRGULE)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_scan_token(IDENTIFIANT)) return true;
    return false;
  }

  static private boolean jj_3_35() {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3_32() {
    if (jj_scan_token(LTE)) return true;
    return false;
  }

  static private boolean jj_3_42() {
    if (jj_scan_token(38)) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_3R_19()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_34()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_scan_token(TYPE)) return true;
    if (jj_scan_token(IDENTIFIANT)) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_scan_token(IDENTIFIANT)) return true;
    if (jj_scan_token(PAROUVR)) return true;
    return false;
  }

  static private boolean jj_3_23() {
    if (jj_scan_token(DIV)) return true;
    return false;
  }

  static private boolean jj_3_31() {
    if (jj_scan_token(37)) return true;
    return false;
  }

  static private boolean jj_3_22() {
    if (jj_scan_token(MUL)) return true;
    return false;
  }

  static private boolean jj_3_21() {
    if (jj_scan_token(SUB)) return true;
    return false;
  }

  static private boolean jj_3_20() {
    if (jj_scan_token(ADD)) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_3R_16()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_27()) {
    jj_scanpos = xsp;
    if (jj_3_28()) {
    jj_scanpos = xsp;
    if (jj_3_29()) {
    jj_scanpos = xsp;
    if (jj_3_30()) {
    jj_scanpos = xsp;
    if (jj_3_31()) {
    jj_scanpos = xsp;
    if (jj_3_32()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_scan_token(VIRGULE)) return true;
    if (jj_3R_6()) return true;
    return false;
  }

  static private boolean jj_3R_6() {
    if (jj_scan_token(TYPE)) return true;
    if (jj_scan_token(IDENTIFIANT)) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3_26() {
    if (jj_scan_token(PAROUVR)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(PARFERM)) return true;
    return false;
  }

  static private boolean jj_3_30() {
    if (jj_scan_token(NEQ)) return true;
    return false;
  }

  static private boolean jj_3R_7() {
    if (jj_3R_6()) return true;
    return false;
  }

  static private boolean jj_3_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) {
    jj_scanpos = xsp;
    if (jj_3_22()) {
    jj_scanpos = xsp;
    if (jj_3_23()) return true;
    }
    }
    }
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_5() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_18() {
    if (jj_scan_token(IDENTIFIANT)) return true;
    return false;
  }

  static private boolean jj_3_25() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_18()) {
    jj_scanpos = xsp;
    if (jj_3_19()) return true;
    }
    xsp = jj_scanpos;
    if (jj_3_24()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_29() {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_26()) return true;
    }
    return false;
  }

  static private boolean jj_3_16() {
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_5()) return true;
    return false;
  }

  static private boolean jj_3_19() {
    if (jj_scan_token(NOMBRE)) return true;
    return false;
  }

  static private boolean jj_3_28() {
    if (jj_scan_token(GT)) return true;
    return false;
  }

  static private boolean jj_3_17() {
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_10() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3_17()) return true;
    }
    return false;
  }

  static private boolean jj_3_43() {
    if (jj_scan_token(39)) return true;
    return false;
  }

  static private boolean jj_3_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_39()) {
    jj_scanpos = xsp;
    if (jj_3_40()) return true;
    }
    return false;
  }

  static private boolean jj_3_39() {
    if (jj_scan_token(IDENTIFIANT)) return true;
    if (jj_scan_token(AFFECT)) return true;
    return false;
  }

  static private boolean jj_3_40() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3_15() {
    if (jj_scan_token(ELSE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) return true;
    }
    return false;
  }

  static private boolean jj_3_27() {
    if (jj_scan_token(LT)) return true;
    return false;
  }

  static private boolean jj_3_37() {
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(PAROUVR)) return true;
    return false;
  }

  static private boolean jj_3_14() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_scan_token(IDENTIFIANT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_42()) {
    jj_scanpos = xsp;
    if (jj_3_43()) return true;
    }
    return false;
  }

  static private boolean jj_3_12() {
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_7()) return true;
    return false;
  }

  static private boolean jj_3_36() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public miniCTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  /** Whether we are looking ahead. */
  static private boolean jj_lookingAhead = false;
  static private boolean jj_semLA;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[43];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public miniC(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public miniC(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new miniCTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public miniC(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new miniCTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public miniC(miniCTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(miniCTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[40];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 40; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 43; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
            case 38: jj_3_39(); break;
            case 39: jj_3_40(); break;
            case 40: jj_3_41(); break;
            case 41: jj_3_42(); break;
            case 42: jj_3_43(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
